id: I8C6D241D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T16:23:23+00:00'
last_modified: '2022-06-07T16:47:51.227298+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30076
  title: གཡུང་དྲུང་བོན་གྱི་ཞལ་འདོན་ཉུང་བསྡུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    51B7:
      image_group_id: I5784
      title: ''
      total_pages: 142
      order: 1
      base_file: 51B7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
