id: P002987
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:32:46.384759
source_metadata:
  id: bdr:W30076
  title: གཡུང་དྲུང་བོན་གྱི་ཞལ་འདོན་ཉུང་བསྡུས
  author: ''
  volumes:
    d2d564a9c50f4e098f37bb8dc12cfc95:
      image_group_id: I5784
      title: ''
      volume_number: 1
      total_pages: 142
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
